import categoryEmbeddingsJson from './categoryEmbeddings.json';

import { HttpError } from '../../httpError';
import { getLog } from '../../requestLogContext';
import { cosineDistance } from './dbscanCosine';
import { hashEmbedding } from './merchantsEmbedder';
import {
  CATEGORY_LABELS_V2,
  CATEGORY_MAP_V2,
  REGEX_RULES_V2,
} from './taxonomyV2';

export type MatchType = 'RULE' | 'ML' | 'INHERITED';

export type CategorySuggestion = {
  category: string;
  confidence: number;
  match_type: MatchType;
};

/**
 * Committed `categoryEmbeddings.json` (generated by
 * `ml-training/scripts/export_category_embeddings.py` from `CATEGORY_MAP_V2` in `taxonomyV2.ts`).
 */
type CategoryEmbeddingsFile = {
  /** Sentence-transformers model id used to produce `vectors` (e.g. `all-MiniLM-L6-v2`). */
  model: string;
  /** Category label strings in the same order as `vectors` rows; keys of `CATEGORY_MAP_V2`. */
  labels: string[];
  /** L2-normalized MiniLM embedding per label — one row per category description. */
  vectors: number[][];
};

const json = categoryEmbeddingsJson as CategoryEmbeddingsFile;

const MISMATCH =
  'Category embeddings are out of sync with the server taxonomy. Regenerate backend/src/services/import/categoryEmbeddings.json from ml-training/scripts/export_category_embeddings.py.';

/**
 * Fails the import with 500 if `categoryEmbeddings.json` and `CATEGORY_MAP_V2` have drifted
 * (missing labels) or `vectors` length does not match `labels` length.
 */
function assertCategoryEmbeddingsMatchTaxonomy(): void {
  const missing: string[] = [];
  for (const label of json.labels) {
    if (!(label in CATEGORY_MAP_V2)) {
      missing.push(label);
    }
  }
  if (missing.length > 0) {
    getLog().error('categoryEmbeddings.taxonomy_mismatch', {
      missingLabels: missing,
      labelsInJson: json.labels.length,
    });
    throw new HttpError(500, MISMATCH, {
      error: MISMATCH,
      code: 'CATEGORY_TAXONOMY_MISMATCH',
      missingLabels: missing,
    });
  }
  if (json.vectors.length !== json.labels.length) {
    getLog().error('categoryEmbeddings.vectors_length_mismatch', {
      labels: json.labels.length,
      vectors: json.vectors.length,
    });
    throw new HttpError(500, MISMATCH, {
      error: MISMATCH,
      code: 'CATEGORY_VECTORS_LENGTH_MISMATCH',
    });
  }
}

function categoryDescriptionsInLabelOrder(): string[] {
  return json.labels.map((label) => CATEGORY_MAP_V2[label]!);
}

/** MiniLM-aligned vectors from committed JSON (same model as ml-training export). */
export function loadCategoryVectorsMiniLm(): Float32Array[] {
  return json.vectors.map((row) => new Float32Array(row));
}

/** When merchant embeddings use the hash fallback, embed taxonomy text the same way. */
export function loadCategoryVectorsHash(): Float32Array[] {
  return categoryDescriptionsInLabelOrder().map((d) => hashEmbedding(d));
}

export function loadCategoryVectors(usesMiniLmMerchants: boolean): Float32Array[] {
  assertCategoryEmbeddingsMatchTaxonomy();
  return usesMiniLmMerchants
    ? loadCategoryVectorsMiniLm()
    : loadCategoryVectorsHash();
}

export function ruleMatchForText(cleanedUpper: string): CategorySuggestion | null {
  for (const [re, category] of REGEX_RULES_V2) {
    if (re.test(cleanedUpper)) {
      return { category, confidence: 1, match_type: 'RULE' };
    }
  }
  return null;
}

export function mlMatchForEmbedding(
  embedding: Float32Array,
  categoryVectors: Float32Array[],
): CategorySuggestion {
  let bestI = 0;
  let bestSim = -1;
  for (let i = 0; i < categoryVectors.length; i++) {
    const sim = 1 - cosineDistance(embedding, categoryVectors[i]!);
    if (sim > bestSim) {
      bestSim = sim;
      bestI = i;
    }
  }
  const label = json.labels[bestI] ?? CATEGORY_LABELS_V2[bestI]!;
  return {
    category: label,
    confidence: Math.round(bestSim * 100) / 100,
    match_type: 'ML',
  };
}
